### ISSUE TITLE
Perl 6, if renamed, needs new filename extensions

### ISSUE THREAD

**Issue by ajs** [perl6/problem-solving#101]
Perl 6 renaming is being discussed in ["Perl" in the name "Perl 6" is confusing and irritating](https://github.com/perl6/problem-solving/issues/81). This is not that.

The issue at question is, if the renaming happens as outlined there (to "Raku") then what are the new filename extensions? It was suggested that we should take this discussion to a new issue, and so here it is.

Current issues are:

* What should the primary code filename extension be? (current contenders are `.raku` and `.rk`)
* Should modules have their own extension? (current contenders are "no" and `.rkm`)
* Should tests have their own extension? (currently there is not a suggestion, but I think "no" and `.rkt` would be the obvious choices)
* Should documentation (Perl 6 POD) have its own extension? (currently I only see `.rd` as a proposal, but `.rpod`, `.rakupod` and `.rakudoc` are also potentially useful. It should also be noted that `.pod6` isn't necessarily out of the question, given that it's not "Perl" specific and is currently recognized.
* Some older editors expect `.rk` to relate to an obsolete file format.

Am I missing anything?

Pinging parties involved in the original discussion: @AlexDaniel @duncand @vrurg

**Comment by ajs** [comment]
@AlexDaniel My dyslexia was going strong. I re-read your title edit three times I still didn't see it! Thanks!

**Comment by ajs** [comment]
My personal take is that:

* Code should be `.raku`. It's clear, short and doesn't bow to 90s Windows conventions.
* Modules should also be `.raku` because nothing needs to parse them differently... the only issue is that of identifying modules when auto-packaging and I feel like we don't know how that will happen in Raku well enough to assign a filename extension for it. It's also not necessary in many other HLLs.
* Tests should live in a descriptively named directory (we tend to use `t` in the Perl community, but `tests` is equally acceptable) but the tests themselves really don't need their own extension.
* Documentation is a unique format, and as such deserves its own extension. I think `.rakupod` works well and it being longer makes sense for documentation: `clear > terse`.

**Comment by AlexDaniel** [comment]
> Am I missing anything?

To clarify, we already have [this pull request](https://github.com/perl6/problem-solving/pull/89) which says this:

> The extension `.rk` for scripts, `.rkm` for modules, and `.rd` for
documentation (POD6) will become the defacto standards for files containing
`Raku` code or documentation.

I don't mind discussing if something else should be used, but these are exactly what we'll use if the PR goes through.

**Comment by ugexe** [comment]
> the only issue is that of identifying modules when auto-packaging and I feel like we don't know how that will happen in Raku well enough to assign a filename extension for it. 

How do we not know? `-I some-dir` has to do *something* if there is no `META6.json`, and if modules shared a file extension with scripts and tests then `-I. some-dir-without-meta6` would have to somehow figure out `bin/foo.raku` and `t/bar.raku` shouldn't be called with `bin::foo` and `t::bar` (and lets not get into if an e.g. `lib/bin/foo.raku` also exists). We don't get to reinvent everything or throw away existing architecture because a name is changing -- a name change must accommodate existing architecture.

**Comment by AlexDaniel** [comment]
> Documentation is a unique format, and as such deserves its own extension. I think .rakupod works well and it being longer makes sense for documentation: clear > terse.

If rakupod is “clear”, then what is “pod”? :) My hope is that “POD” as a name will go away, and it'll become just “RakuDoc” or similar. “.rakudoc” is fine for me but people tend to prefer short extensions (e.g. “.md” vs “.markdown”, even though “.markdown” is supported by most things). So the current `.rd` proposal is perfectly fine for me.

> Tests should live in a descriptively named directory (we tend to use t in the Perl community, but tests is equally acceptable) but the tests themselves really don't need their own extension.

The whole `.t` thing is really weird, and it seems like tools are supposed to assume that `.t` files are perl5 executables even though there's no shebang, which doesn't really make much sense to me. At some point people started to use `.t6`, which makes the situation even weirder.

As for modules, what @ugexe says sounds about right.

**Comment by nxadm** [comment]
I agree with @AlexDaniel. While I don't think that the extension distinction between "scripts" and "modules" makes much sense (or even the use of extensions for executables in UNIX), I think this is a discussion for later because we need to minimize unintended consequences in the transition period as @ugexe points out.

**Comment by jnthn** [comment]
On Windows, file extensions are used to determine an association with an interpreter. Thus, the distinction between scripts (entrypoints that we should run) and modules (things that aren't to be run directly) is carried by the file extension, not a `+x`.

**Comment by ajs** [comment]
@ugexe I'm not sure what you mean. Is there some special handling that is unusual among HLLs, here? When I currently run:

```$ perl6 -I lib -e 'use Foo::Bar'```

It is very clear what has to happen, regardless of what the filename on `Foo` is. Load it, parse it in a namespace based on its path (`Foo/Bar -> Foo::Bar`) and import from it. 

But if I do:

```$ perl6 -I lib lib/Foo/Bar.pm6```

Then it's also equally clear what should be happening. Load the named file, compile and execute its RUN-MAIN if available.

This is exactly the way Perl 5 and Python work, for example.

Does it do something else in Rakudo today that I'm not aware of?

**Comment by nxadm** [comment]
> On Windows, file extensions are used to determine an association with an interpreter. Thus, the distinction between scripts (entrypoints that we should run) and modules (things that aren't to be run directly) is carried by the file extension, not a `+x`.

@jnthn, I was under the single file extension model is not a problem for Python and Ruby on Windows. Do they do something differently?

**Comment by jnthn** [comment]
@nxadm It's not a *problem*, I'm just pointing out that the distinction has a use.

**Comment by jnthn** [comment]
Noting this:

> I think this is a discussion for later

And this:

> I don't mind discussing if something else should be used, but these are exactly what we'll use if the PR goes through.

I'd like to note that while I've not got especially strong feelings on the exactly extensions we choose, I *really* want it settled as part of the renaming PR. I say this as somebody invested heavily in building Perl 6 development tooling; the Raku name changes is already going to make extra work for us, which is OK, but I'd rather do one round of extension changing work, not multiple. I suspect others who will want to update editor plugins etc. would also appreciate clarity on it sooner rather than later.

**Comment by ugexe** [comment]
> @ugexe I'm not sure what you mean. Is there some special handling that is unusual among HLLs, here? When I currently run:

Yes, you are restricting your entire point to `-I lib` and the assumption that all modules are a folder `lib`. This obviously is not the case  with existing behavior when one does `echo ... > foo.pm6; perl6 -I. -Mfoo -e ''` which your suggestion would break.

**Comment by ajs** [comment]
@ugexe It seems like @jnthn would prefer that this not be the place that this get resolved, but I would like to understand your technical point. I certainly was not presuming "lib" as a directory name. It was an example. I do not see why `perl6 -I. -Mfoo -e ''` should break. It's going to:

* Set the include path to include `.`
* Search the include path for `foo.<ext>` where <ext> is whatever we want it to be (e.g. `.raku`)
* Because `-Mfoo` means `use foo` we are then going to read the file, compile it under the namespace identified by its path (e.g. `::foo`) and import from it.

This does not break because you named the file `.raku`.

I think you are making a presumption of more magic than there really is... can you cite the specific code in rakudo that you are referring to?

**Comment by Leont** [comment]
> Tests should live in a descriptively named directory (we tend to use t in the Perl community, but tests is equally acceptable) but the tests themselves really don't need their own extension.

People can and do put other files into the `t/` directory, most obviously helper modules but sometimes also reference files. As such, them having an extension to differentiate them from the rest is certainly useful.

> The whole .t thing is really weird, and it seems like tools are supposed to assume that .t files are perl5 executables even though there's no shebang, which doesn't really make much sense to me. At some point people started to use .t6, which makes the situation even weirder.

It's a bit more complicated than that. `prove`/perl5 will actually respect the shebang **unless the shebang contains the word perl**. Ironically, we would have never needed `.t6` if the language's name was not "perl6" now.

`prove6` always assumed both `.t` files were perl6.

**Comment by AlexDaniel** [comment]
Amazing.

**Comment by ugexe** [comment]
> Search the include path for foo.<ext> where is whatever we want it to be (e.g. .raku)

and when there is `foo.p6` and `foo.pm6` we run into the same ambiguous non-sense as allowing `.pm` in addition to `.pm6`. Additionally "search the include path" is not true of a META6.json exists, so lets not pretend it is so simple.

> Because -Mfoo means use foo we are then going to read the file, compile it under the namespace identified by its path (e.g. ::foo) and import from it.

Scripts aren't precompiled, so `-Mfoo` pointing at a `foo.raku` is going to Do The Wrong Thing because of ambiguity

**Comment by Grinnz** [comment]
`.t` is not meant to be specific to Perl 5, and in fact very few online resources tie it to Perl 5, but in practice it no other language other than Perl 6 has adopted it for this purpose. So the primary reason not to use `.t` would be to disambiguate for things other than the interpreter that rely on the file extension and currently assume `.t` is Perl 5 due to usage: editors, github categorization, Windows file associations. That said, I honestly don't think this is a decision that needs to be made at all unless you really want to introduce something new for it like `.rkt` - it seems more like a choice of ecosystem convention.

**Comment by vrurg** [comment]
> `.rkt` - it seems more like a choice of ecosystem convention.

This choice could be a recommendation. Like no one enforces a repository to be prefixed with `perl6-` (or possibly `raku-`), but it's an appreciated practice.

**Comment by ugexe** [comment]
I'd also like to make a point: the last time the community decided to bike shed on something they had little/no skin in the game on it ended up with *me* doing all the work (zef, travis, etc) despite not being a proponent of it (the `.t6` extension). We need people willing to implement things, not more ideas.

**Comment by Leont** [comment]
> This choice could be a recommendation. Like no one enforces a repository to be prefixed with perl6- (or possibly raku-), but it's an appreciated practice.

Not at all. The various tools (zef, mi6, prove6, …) need to agree on this sort of thing to cooperate. Your choice of test extension is much more than a recommendation if the result of not abiding by the convention is that your tests don't get to be run.

**Comment by AlexDaniel** [comment]
> I'd also like to make a point: the last time the community decided to bike shed on something they had little/no skin in the game on it ended up with _me_ doing all the work (zef, travis, etc) despite not being a proponent of it (the `.t6` extension). We need people willing to implement things, not more ideas.

I looked at https://github.com/perl6/user-experience/issues/36 at it seems there were several people contributing various bits.

**Comment by ugexe** [comment]
> I looked at perl6/user-experience#36 and it seems there were several people contributing various bits.

If we want to be pedantic then fine: I did *most all* of the work.

**Comment by ajs** [comment]
@ugexe we might have just been misunderstanding each other. I agree that supporting more than one filename extension is error-prone, and I don't recommend it. But if you have a `foo/bar.raku` and a `lib/foo/bar.raku` and you then run `raku -Ilib -Mfoo::bar -e ''` then you are absolutely going to have to rely on search order to resolve which one you get. That's not a bug, it's what you explicitly asked for.

I thought you were saying that there was some magical compiler feature that was turned on for files with a "module" extension as opposed to a "program" extension other than which ones will be acknowledged by a "use" vs. explicit file reference.

**Comment by jnthn** [comment]
> I agree that supporting more than one filename extension is error-prone

If I understand correctly, I think what @ugexe is arguing is that having different extensions for script vs. module makes things *less* error-prone, because `-M` and `use` will only ever load something that is intentionally a module.

**Comment by jnthn** [comment]
> It seems like @jnthn would prefer that this not be the place that this get resolved

It's fine to discuss it here, I'm just saying that the extensions described in #89 will - if the rename is approved - be what we end up with. There's still time for for that to change as a result of the discussion here. At this point my feeling is:

* Short is preferable (it's common, so is worth huffmanizing)
* The script/module distinction is worth retaining
* If we're going to have `.rkm` for Raku Module, then Raku Doc should be `.rkd`, not the proposed `.rd` (that gives us a productive prefix, which the suggested `.rkt` - should we determine it has value - would also follow).
* The "do we really need something other than `.t`" decision can be deferred

**Comment by AlexDaniel** [comment]
> The "do we really need something other than .t" decision can be deferred

Maybe, but people are already using `.t6`.

**Comment by kentfredric** [comment]
I should probably mention a primary reason for me with wanting different extensions for various formats is for co-existence purposes.

Whatever extension is chosen, it should be able to support somebody doing:

```
  lib/Foo.x    # the source code
  lib/Foo.y    # documentation for Foo.x
  lib/Foo.z    # "unit" tests for Foo.x
```

Even though that last one may be uncommon.

Just some background as to why:

- In Rust, you can define tests inside a given unit, inline, and they share the visibility rules of other code defined in the unit.
- Tests defined in a tests/ dir are considered "Outside" the unit, and you have to abide by the public interface rules.
- But having the tests in the unit itself ... is a bit annoying.

So subsequently, I kinda wish I could define tests some way that shared the visibility rules of a unit, but not inherently a member of that unit.

I imagine there could be some conceptual bleed-through into Raku that makes people want to make similar choices.

**Comment by vendethiel** [comment]
>     * which the suggested `.rkt` - should we determine it has value - would also follow).

Not sure how happy the Racket folks are gonna be about this one..:)

**Comment by ajs** [comment]
> > I agree that supporting more than one filename extension is error-prone
> 
> If I understand correctly, I think what @ugexe is arguing is that having different extensions for script vs. module makes things _less_ error-prone, because `-M` and `use` will only ever load something that is intentionally a module.

I'm not sure that I agree, but that wasn't the part of the comment I was replying to. I was noting the mutual agreement that if there is more than one MODULE filename extension that have to be disambiguate, I agree that that is going to be a source of issues (and is, today). How serious is anyone's guess, but Python does fine with just one filename extension, AFAIK, so if we're arguing that one filename extension is going to cause issues, I'd like to know what the basis for that claim is.

**Comment by ajs** [comment]
@kentfredric That is a very non-standard use-case, and I'm not sure that it really merits a major feature of all development in order to support. Tests generally get grouped together as `t` or `tests` and docs usually get grouped together as `doc` or `docs`. That's a pretty wide-ranging convention.

If you want everything in one place, then just put them all in the same file. Rubar ne Perl 6 handles that just fine.

**Comment by ajs** [comment]
> > The "do we really need something other than .t" decision can be deferred
> 
> Maybe, but people are already using `.t6`.

They (at least in my case) are doing so because tests conventionally are `.t` but editors such as sublime, which I use, don't want to treat things that end in `.t` as Radish ne Perl 6, they want to treat it as Perl 5. It's purely defensive. If everything were `.raku` then I would never need a `.trhubarb`.

**Comment by nxadm** [comment]
@ajs
> If you want everything in one place, then just put them all in the same file. Rubar ne Perl 6 handles that just fine.

Go doesn't use a special file extension for tests but the "_test" suffix to the basename (e.g. foo.go and foo_test.go). To be run as tests, functions in the test files must start with "Test" (e.g. TestAddFoo() is supposed to test AddFoo()). 

I am not advocating for adopting Go's way of testing (as it's very different of what we do), but just pointing out that having the tests in the same place as the regular code as the advantage to make visually clear what source file is not yet tested. It's easy to forget an almost empty "t" dir.

(Tests and extended docs in the source file is not something I like very much.)

**Comment by ugexe** [comment]
> that one filename extension is going to cause issues, I'd like to know what the basis for that claim is.

Why do you think a name change is the ideal opportunity to make *functional* changes throughout various parts of the Perl 6 ecosystem? Again, scripts do not get precompiled and use different schematics for being loaded, so why should we get rid of the *obvious* way of discerning? To make sublime text easier to setup...?

**Comment by ajs** [comment]
> > but Python does fine with just one filename extension
> 
> Isn't that the reason they do that strange thing?
> 
> ```python
> if __name__ == "__main__":
>     main()
> ```

I think there's some substantial confusion here. There are two issues:

1. Are there technical impediments to any given filename extension?
2. What should community standards be around filenames.

The equivalent of the above in Perl 6 is:

```
$ cat x/y.pm6 
sub MAIN() { say "yes" }
```

Which as you can see, works exactly as the python in both contexts:

$ perl6 -I. -Mx::y -e ''
$ perl6 x/y.pm6 
yes
```

Whether we like that or not, and whether we tell people that that is something their modules should be doing is a matter of community expectations and standards, and should have nothing to do with this conversation!

Today, the universal filename extension CAN BE `.pm6`, but we, as a community, do not generally advise that people name their scripts `myscript.pm6` by convention. There is nothing technical preventing that, however!

**Comment by ajs** [comment]
> > that one filename extension is going to cause issues, I'd like to know what the basis for that claim is.
> 
> Why do you think a name change...

I don't understand how this is an answer to the question.

We've already ended the "what should the extensions be" discussion, here. I take @jnthn as authoritative on that. However, I did ask that someone explain the claim that there are technical issues with `.raku` that make it unusable. I have yet to hear what those technical issues are other than in the case where we support more than one module naming convention (e.g. if we supported `.rakumod` and `.raku` at the same time ***as module lookup extensions*** which I agreed with you was a terrible idea).

> scripts do not get precompiled and use different schematics for being loaded, so why should we get rid of the obvious way of discerning?

This is misleading, as I pointed out above. The above script absolutely does get precompiled *when it is used as a module* but it does not when it is invoked directly. Today. In Rakudo.

If we do not select a module naming convention and instead keep one name for everything, nothing technical breaks. That's all I'm trying to establish, here.

**Comment by ugexe** [comment]
You think that script gets precompiled in such a way that it can be useful to anything else? But nevermind me, just do whatever since I literally don't have time to teach every little facet of a complicated system to whomever wishes to bike shed.

A topic about file extensions with 36 replies... death by committee at its finest. Please do not @ me in this thread again.

**Comment by duncand** [comment]
Thank you @ajs ,

I prefer `.raku` as the filename extension for all Raku source code files.

* In the modern day when we don't have technical limitations making every byte precious, the greatly enhanced readability of `.raku` (merely 4 characters) wins out.

* We have a much smaller mental burden, not having to keep track of a variety of different name variants of Raku; we see `.raku` and we know its Raku source; we don't have to see `.rk` or similar and unpack that as Raku versus say TCL (`.tk`) or various other much more similar extensions.

* We have much better searchability and indexability; performing searches on Google for "raku" can more easily bring up source files even if they aren't separately documented with the 4 letters, and not just human prose.

* There is no benefit to an extra file extension to differentiate main programs and modules; in practice any Raku source file can be directly executed or be used as a library no matter what its filename is.

* In practice on any modern project layout, main programs and libraries are kept in different locations, such as under bin/ and lib/ subdirectories, which provides the needed context and separation, or main programs would tend to be located closer to the main folder and libraries be more nested.

* Fewer extensions for Raku source means less complexity for editors or IDEs or other tooling.

I also prefer `.rakudoc` over other alternatives.

* While `pod` has history and is more language-agnostic, its versions were still co-developed with and are generally only embedded in Perl or Raku source files respectively, if not in their own files, so including `raku` in the name is just more descriptive, its the documentation format codefined with the Raku language.

* Its easier to understand at a glance for average people that `doc` is documentation while `pod` could sound like an archive format or something.

* Despite its history, please keep numbers like `6` out of the extension, that doesn't really help anything.

For test files, I think `.raku` is also best, and helps editors that mainly conceptualize files on their extension, whereas `.t` means they would have to interpret shebang lines or such to know how to syntax color it or whatever; they can still live in a DIRECTORY named `t`, or `test`.

**Comment by duncand** [comment]
> > Am I missing anything?
> 
> To clarify, we already have [this pull request](https://github.com/perl6/problem-solving/pull/89) which says this:
> 
> > The extension `.rk` for scripts, `.rkm` for modules, and `.rd` for
> > documentation (POD6) will become the defacto standards for files containing
> > `Raku` code or documentation.
> 
> I don't mind discussing if something else should be used, but these are exactly what we'll use if the PR goes through.

@AlexDaniel You are absolutely right.

In fact, the reason I started this whole extension thread is precisely because I didn't have priivileges to put my comments on that pull request, where ostensibly it belongs.

I hope that someone with privileges will see this current thread and look to modifying that pull request to reflect the prevailing feedback in this current discussion thread, or alternately to explicitly mark file name extensions as a detail that will be addressed in a separate pull request.

Alternately, may I be granted privileges to comment on that pull request?

@lizmat @vrurg

**Comment by AlexDaniel** [comment]
> Alternately, may I be granted privileges to comment on that pull request?

Sure, done.

**Comment by vrurg** [comment]
To my view, this topic is tainted. Opening a new, more constructive, one would be better. It would start with the following bottom line:

Basic (script) extension must be chosen: wether it be *.raku* or *.rk*. Depending on the choice:

- for *.raku* accompanying extensions are:
   - *.rakulib* or *.rakumod* – TBD
   - *.rakutest* – TBD
   - *.rakudoc* - perhaps, everybody would agree
- for *.rk*
   - *.rkm* 
   - *.rkd*
   - no good option for test files.

**Comment by AlexDaniel** [comment]
@vrurg sure, can you start a new ticket? :)

**Comment by AlexDaniel** [comment]
OK, new ticket [here](https://github.com/perl6/problem-solving/issues/106). Thank you, @vrurg.
