### ISSUE TITLE
A threat of full CORE duplication for each language revision

### ISSUE THREAD

**Issue by vrurg** [perl6/problem-solving#104]
I'm experimenting with making quant hashes iterable. And it looks like a relatively simple task turns into a horrible requirement of copying over all of `CORE.c` into `CORE.e`! Here is why.

`QuantHash does Iterable`, then I started with new `Set` in `CORE.e` which consumes the new iterable `QuantHash`. The resulting class freezes on something like: `"a" ~~ set(<a b c>)` because `ACCEPTS` coerces `"a"` into a `Set` first but it does so using `Set` method on `Any` which itself is a 6.c class and correspondingly it only knows about 6.c version of `Set` and we end up with a new coercion, and so on...

One way to solve it would be to use `nqp::p6getlexclient` in `Any::Set`. But the method signature has `--> Set:D` and apparently it fails with a type check error. A quick solution is to remove return type check altogether because in this particular case it's anyway somewhat redundant. But this could be unaffordable solution for other similar cases.

Another way is to have a dedicated `ACCEPT` in `Set` which would specifically handle `CORE::v6c::Set` and re-coerce it into 6.e `Set`. But this approach has a performance tag attached due to one extra convertion.

The best solution would be for `Any` to know all classes from all COREs but this is only possible if `Any` itself is defined in the latest CORE available. In current model it means that COREs have to be totally duplicated. And this effectively means loading 28mbytes of CORE whenever code requires 6.e – twice of that of CORE.c alone.

**Comment by jnthn** [comment]
> I'm experimenting with making quant hashes iterable

I believe I've already noted elsewhere, at least once, that I'm quite sure that it was intended that they acted as items.

**Comment by vrurg** [comment]
Yes, I know. Just wanted to play a bit to check a few ideas. But that's not the point. This is just how I came to these thoughts. We might get into a similar situation by some other way.

**Comment by jnthn** [comment]
OK, that's fair enough; I'd just hate for you spend so much time on that specific issue when it's questionable if there even should be a change in that regard.

I did [write up some thoughts on this](https://gist.github.com/jnthn/c10742f9d51da80226fa#coresetting-object-change-guidelines) quite a while ago, and had assumed that document was in the Rakudo repository `docs` folder and so assumed you'd have been it, but it seems it's not. Hmm.

**Comment by jnthn** [comment]
OK; just keep in mind it was written 4 years ago, and some things worked out differently. But I think the section I liked, and indeed much else in that file of the gist, is still applicable and relevant.

**Comment by vrurg** [comment]
Would you mind me moving them into docs? I could create a subdir articles/ and add publication dates into the file names.

**Comment by jnthn** [comment]
@vrurg I think the Rakudo and MoarVM versioning parts are perhaps not worth it since they don't really reflect what we ended up doing. The one on guidelines for evolving the language was the part I had thought was already in `docs`, so of course no objections on that being put there!
