### ISSUE TITLE
FQN method call needs support for parameterized roles.

### ISSUE THREAD

**Issue by vrurg** [perl6/problem-solving#110]
There is currently no way to directly dispatch a method call to a parameterized role. Consider the example:

```
role R1[::T] {
    method foo { ... }
}
role R2[::T] {
    method foo { ... }
}
class C does R1[Str] does R2[Int] {
    method foo {
        self.R1[Str]::foo
    }
}
```

**Comment by vrurg** [comment]
It looks to me like it's something for the syntax change because I found no mention of use of parameterizations in FQN calls.

**Comment by lizmat** [comment]
Maybe that's because parameterized roles are generally embedded in a class definition?  And you would refer to that class in a FQN call?

**Comment by lizmat** [comment]
Also, even if you *could* refer to a role, in the call, it would refer to a punned instance of the role, not the role itself.  So maybe that is not what you wanted anyway?

**Comment by jnthn** [comment]
> There is currently no way to directly dispatch a method call to a parameterized role.

There is a way, in fact:

```
role R[::T] { method m() { "x" } }
class C does R[Int] { method m() { "y"} }
constant RInt = R[Int];
say C.RInt::m(); # x
```

Which happily demonstrates that all is well at the MOP level, and so the only matter I think that we need to consider is if there's a desire for syntactic convenience here, and if so how to deliver it.

> Also, even if you could refer to a role, in the call, it would refer to a punned instance of the role

That's not what is happening here. Even methods that are hidden in the target of the composition by some other method still undergo generic instantiation during the composition process; it is this instantiation of the method that we are reaching/calling here.

**Comment by vrurg** [comment]
> Which happily demonstrates that all is well at the MOP level, and so the only matter I think that we need to consider is if there's a desire for syntactic convenience here, and if so how to deliver it.

I think it makes sense but really the question is 'how'?

As to why it does, here is an example:

```
role Interface[::T] { method foo { ... } }
role R1[::T] does Interface[T] { ... }
role R2[::T] does Interface[T] { ... }
class C does R1[Int] does R2[Str] { ... }
```

Somehow method `foo` must be available to the class.

As to 'how', for simple cases with just one role `C.R1::foo` must work, I think. It shouldn't be a big deal to pick the right candidate from concretizations. Worse if:

```
class C does R1[Int] does R1[Str] { ... }
```

This would be a rare situation due to very likely attribute conflicts. Yet it's not impossible at all. Does it worth extending the syntax? Probably not, as I think of it now. Because one could do:

```
role R2Str does R2[Str] { }
class C does R1[Int] does R2Str { ... }
```

Same is currently possible for when it's just one role applied, but why adding to the boilerplate if DWIM can nicely handle it?

Perhaps, I'll try to see if it's not too hard to be implemented as a part of rakudo/rakudo#3199.

**Comment by lizmat** [comment]
Maybe better as a different PR?  As this is just adding syntactic sugar to existing functionality, if I understand this correctly?

**Comment by vrurg** [comment]
Sorry @lizmat, as it sometimes happens to me – thinking was faster than typing, it was unclear what I mean.

After more thorough consideration I don't think a sugar for parameterized FQN is needed. The situation of consumption of the same role but with different parameters is mostly hypothetical. While I'm sure it will take place in future in a project or couple, but it never will be a commonplace. Conclusion: doesn't need to be taken special care of.

What is common is consumption of a single parameterization of a role. In this case DWIM, aka "the principle of least surprise", dictates that:

```
class C does R[Int] {
    method foo {
        C.R::foo
    }
}
```

is expected to work. I.e. it must find `R[Int]` concretization on class `C` and call it's method `foo`. More precise behavior: find _the first_ concretization of role `R` on class `C` and use it.

*Just to think about.* As to the hypothetical situation of consuming different parameterizations of the same role, there is a solution in my previous comment, where dummy `R1Str` role is used. If we ever need a syntax to resolve the conflict then it's better be done via aliasing. Something like `class C does-as<R1Str> R1[Str] { }` or `class C does R1[Str] as R1Str { }`. The `as` alias could then be used to name a `ConcreteRoleHOW` object. This would make it possible for `C.R1Str::foo()`. This would prevent code cluttering with `C.R[Str,Str,Int]::foo` constructs and spare a couple of keyboard clicks for a dev.

**Comment by vrurg** [comment]
Oh, the primary point: because what I propose isn't a syntax change, it fits into the current PR nicely.

**Comment by vrurg** [comment]
**UPD** FQN by the group name works on my PR. This can be closed when 3199 is merged.

**Comment by vrurg** [comment]
Closing with merge of rakudo/rakudo#3199
