### ISSUE TITLE
What's exactly our stance regarding other Raku implementations?

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/problem-solving#124]
When it comes to being welcoming to other Raku implementations, different devs have different opinions on how much we should go out of our way to encourage them. I'd like there to be a consensus or a policy on that. It doesn't have to be very specific, I just want to know the direction, and some basic recommendations on what we should and shouldn't do.

Sometimes people bring the idea of having more than one compiler as an argument for doing things one way or another, especially when it comes to justifying an inconvenience (example: [discussion about a separate rakudo github org](https://github.com/perl6/problem-solving/issues/46#issuecomment-504110472)).

Other times we are completely silent/neutral and let things happen naturally. For example, no one is evaluating how compiler-agnostic `roast` is. For example, we have [tests using `.gist`](https://github.com/perl6/roast/search?p=1&q=gist&type=&utf8=%E2%9C%93), and I'm sure that there are many other things (spread over the whole roast repo) that non-rakudo compilers will have troubles passing.

There are also times when we do steps in a completely opposite direction, making creation of new compilers more difficult and less welcome. For example, “Perl 6 Weekly” was recently renamed into “Rakudo Weekly”, even though it reports on many topics that are not strictly rakudo-related. I do think that a resource like raku weekly can empower smaller projects (like starting a new compiler), but it being a “Rakudo” weekly immediately gives other compilers a second-class citizen status.

_So we are currently not dedicated one way or another, but it's also not a balanced position or a compromise._ It's completely random, and it feels like we're inconveniencing ourselves to achieve nothing in the end. We can do much better if we actually want to encourage other raku implementations.

I think it would really help if we can define some basics. If we're open to other raku implementations, what does it mean, in a few sentences? Generally, what should we do, and what we shouldn't do?

**Comment by duncand** [comment]
If the old name of a blog was "Perl 6 Weekly" why not rename it again to "Raku Weekly" or "Raku Compiler Weekly", depending how broad/focused it is.

**Comment by lizmat** [comment]
My reasoning is that the Perl 6 Weekly has been about the Rakudo implementation only for the past 4+ years, ever since Niecza went into deep hibernation.  For the same reason the executable of Rakudo will become `rakudo`, and `perl6` and `raku` will be symlinks to that, I felt that the Weekly should be called Rakudo Weekly.

**Comment by AlexDaniel** [comment]
@lizmat honestly, that doesn't make any sense. I'm not even sure where to start.

`raku` being a symlink to `rakudo` doesn't mean that rakudo and raku are now synonymous. I see it as being other way around, letting the user choose which compiler to use for `raku`. Ideally, distros should provide means for choosing where `raku` points (e.g. `update-alternatives` on debian).

> Perl 6 Weekly has been about the Rakudo implementation only for the past 4+ years

Latest news about fanlang were in 2017, I think. Fanlang isn't exactly a raku implementation, but it was pretty damn close to that. I don't know if you reported about it on p6weekly, but I would've expected you to. And even if it was 4+ years, why does that matter?

See, this is why I created this ticket.

**Comment by jnthn** [comment]
> I would've expected you to

I think it's up to @lizmat to decide what she wishes to cover when writing the weekly. It's hardly like there's folks queuing up to put in the large amount of work needed to write it each week. Further, leaving the name "raku weekly" available for somebody who *does* want to cover multiple implementations - come such a time that they exist - seems reasonable.

**Comment by AlexDaniel** [comment]
> Perl 6 Weekly has been about the Rakudo implementation only for the past 4+ years

I didn't mean that lizmat should do it one way or another. What I was trying to say is that fanlang was probably mentioned in p6weekly, somewhere, at some point in 2017 or maybe a bit earlier, and I don't think mentions of it would've been omitted intentionally.

> Further, leaving the name "raku weekly" available for somebody who does want to cover multiple implementations

Creating a competing weekly to mention attempts to create a new compiler? Is this a realistic outcome? It doesn't sound very welcoming.

Anyway, are we open to other Raku implementations? If so, what does it mean and what we should and shouldn't do?

**Comment by jnthn** [comment]
> It doesn't have to be very specific, I just want to know the direction, and some basic recommendations on what we should and shouldn't do.

Mostly, we should try to avoid Rakudo being seen as the "official" or "reference" implementation.

> Other times we are completely silent/neutral and let things happen naturally. For example, no one is evaluating how compiler-agnostic roast is. 

That's not an easy task when there isn't another compiler to show such things up, though the multiple backends for Rakudo at least helps a bit.

> For example, we have tests using .gist

I thought the `.gist` output *was* specified, and it's the `.perl` output that we should not be over-specifying.

> I'm sure that there are many other things (spread over the whole roast repo) that non-rakudo compilers will have troubles passing

Aside from "citation needed", it's not like getting Rakudo passing them has been easy either. :-)

> If we're open to other raku implementations, what does it mean, in a few sentences? Generally, what should we do, and what we shouldn't do?

I think "open to" actually captures it nicely: we needn't focus on trying to get folks to starting new implementations as opposed to working on Rakudo, but if somebody comes along with one, or expresses interest in working on one, then they should know that:

* It's roast that determines whether something is a Raku implementation or not, rather than Rakudo being the "blessed" implementation
* If there are things in roast that are unreasonable, or things that aren't specified in roast where another implementation thinks they should be done differently, then we'll be open to making things better as appropriate

Raku is the richer for there having been competing implementation efforts in the past, and I'd gladly see it be enriched by others in the future.

**Comment by AlexDaniel** [comment]
OK, I got my question answered. So there's nothing to it. Raku is defined by Roast, and also Raku and Rakudo are separate projects. That's it, OK.

Indeed, then it doesn't matter whether roast is usable or if it's raku or rakudo weekly. I somehow assumed that we wanted to create an inviting environment with at least a bit of support from our side, but it's just my misunderstanding.

I see no point creating a document and submitting it as a PR because there's nothing to write down.

Thanks!

**Comment by lizmat** [comment]
FWIW, *if* there would be a competing implementation, I would definitely mention it in the Rakudo Weekly, at least to let people know of its existence.  There have been other OT mentions in weekly issues, so why not one like that.

I just want to make clear to everybody that the Rakudo Weekly is aimed at Raku on Rakudo, not on any other implementation.  And indeed, should someone decide to do a meta-aggregator of all Raku implementation, then at least "Raku Weekly" would not be squatting on that.

About creating an inviting environment: if other implementation seek wisdom from Rakudo people, we will provide these just as easily as we would any other Raku / Rakudo question.  This is open source, after all, we shouldn't need to have any secrets from each other, and we should all be supportive of each other.  That does however, not imply that we're going to be doing somebody else homework.
