### ISSUE TITLE
Release manager for Rakudo 2019.12 and onward

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/problem-solving#132]
To make it clear, I'm still here, I just want to focus on other raku things.

[It was a wild ride](https://github.com/rakudo/rakudo/blob/master/docs/release_guide.pod#releases-so-far), but after 2+ years I no longer have enough energy for new releases, and rakudo definitely deserves more.

To clarify, @kawaii previously agreed to take over, but lately they have been busy with other real life stuff. So it seems that we still need a new release manager.

Please leave a comment if you're interested! Note that it's a good opportunity for those who haven't heavily participated in rakudo development, it's definitely one of the ways to get more involved :)

**Comment by JJ** [comment]
Just wanted to thank you for your work so far.
I've already said so many times, but for me, the first part of every year has a lighter workload. That means that from February on I could take over if you'd take me, but definitely not now (and I would still have to leave in September, when new students come my way)

**Comment by nxadm** [comment]
Great job, @AlexDaniel . You've always been someone very pleasant to work with!

**Comment by Xliff** [comment]
@AlexDaniel - Thanks for all the hard work!

**Comment by vrurg** [comment]
@AlexDaniel take my appreciation too! Thanks for the great job!

**Comment by Altai-man** [comment]
Thanks a lot for the insane amount of work put into this! You are awesome.

I would like to propose myself for the role of new release manager.

Pros be (the order is random):

* For some time I am doing the same work with Comma (changelogs, talking with people about releases, testing, doing builds, updating metadata for the website etc), just at a smaller scale, of course.
* Due to my work, I am pretty tied to Raku community, and it is unlikely for me to suddenly disappear.
* I would like us to have high paced releases, which means bringing back monthly releases. This can be considered a cons, but I really think that we need some freshness and ship fixes and improvements more often, shortening the feedback cycle.

Cons be:

* I am not especially familiar with rakudo internal details, so will ask about better decisions WRT to blockers and issues of this sort. Please, be gentle.
* Right now, I don't have a setup to run Blinn, it is close to being impossible. @AlexDaniel++ said we'll have a nice setup for this with @rba++ help. This is more of a requirement than a cons, I think.

I need to do a PR following the standard procedure, right?

**Comment by AlexDaniel** [comment]
I think @Altai-man is a great candidate. From what I've seen they're very responsible and willing to do their best. Not knowing a lot about Rakudo internals is not an issue, if we had that requirement it would narrow down the search to existing rakudo developers and I'd much rather not distract them from their work. To be honest I never had that knowledge too.

> I need to do a PR following the standard procedure, right?

I don't think it's needed. @jnthn, do we want to have the release manager engraved in the problem-solving repo? I fail to find a good reason to do that. It made sense for infrastructure stuff, but it's much simpler with release management.

I think a PR tweaking this document is enough: https://github.com/rakudo/rakudo/blob/master/docs/release_guide.pod#planned-future-releases (put your name inside the parens).
Also, feel free to add planned dates for upcoming months if you strongly feel about doing monthly releases.

**Comment by jnthn** [comment]
> @jnthn, do we want to have the release manager engraved in the problem-solving repo? I fail to find a good reason to do that.

No, I don't think that's required; just sign up in the mentioned document. :+1: from my side on returning to monthly releases, if time/energy allows.

**Comment by JJ** [comment]
:+1: for @altai-man

**Comment by nxadm** [comment]
@Altai-man and @JJ would be great release managers. Looking forward to package their releases!

**Comment by vrurg** [comment]
BTW, I think @nxadm have a good point here. I see no good reason of not having two release managers. If once can't do the job for any reason, the other one can pick it up the task.

**Comment by AlexDaniel** [comment]
I think there's enough responsibility on @JJ's shoulders. Note that anyone can help the release manager by contributing to the changelog, helping find the regressions, resolving blockers, etc. If someone does that enough then surely they can be mentioned in the release guide, but I don't think we should appoint more than one person.

**Comment by vrurg** [comment]
My point was in having a backup variant only. I.e. @JJ wouldn't be doing a release most of the time if ever. And only if he applies voluntarily for this role, for sure!

**Comment by rba** [comment]
@AlexDaniel great work. I thank you.

👍 for @Altai-man

Off-topic @Altai-man: Regarding Blin: @maettu and then Konrad, dig deep to find some machines. Looks like with the current amount of modules in ecosystems allows to have Blin runs 2x a day on the hardware we found. Will come back to you in December with this, to be able to run Blin regularly and put the results somewhere automatically.

**Comment by Altai-man** [comment]
The contributor license agreement for Rakudo is signed and confirmed by Coke.
I'll update the schedule after getting rights to commit to the repo.

In the meanwhile, I am having some steady progress with exploring the release script. My gut feeling is I'll spend some time to make it even more awesome.
The planned release date is 22th, I hope:
* By the end of this week I'll sort out the releaseable usage.
* Next week I'll dedicate at looking at commits.
* At the beginning of the third week I am assuming that 1)Blin is working; 2)I am starting to look at possible blockers, write the changelog, bump things, heading towards the weekend.

**Comment by AlexDaniel** [comment]
@Altai-man I think you've got a good grip on things now. Feel free to ping me if you need any info.

I think this issue is now resolved.
