### ISSUE TITLE
Please add me to list of reviewers

### ISSUE THREAD

**Issue by lizmat** [perl6/problem-solving#14]
As described in the README.

**Comment by lizmat** [comment]
I could not assign the "meta" label myself.

**Comment by AlexDaniel** [comment]
Sure!

Aand… I messed up the commit title. :)

**Comment by lizmat** [comment]
Thanks!

**Comment by lizmat** [comment]
Am I supposed to be able to assign / create labels now?

**Comment by AlexDaniel** [comment]
> Am I supposed to be able to assign / create labels now?

Not exactly. The assigning is done according to [this list](https://github.com/perl6/problem-solving#labels-and-responsible-devs) and I'm hoping to automate it somewhat (maybe with issue templates). Generally, this is not something you should worry about.
