### ISSUE TITLE
kiss camelia goodbye

### ISSUE THREAD

**Issue by eiro** [perl6/problem-solving#140]
camellia gives newcomers a bad feeling about the language

according to the reactions i had the chance to observe (mostly students), camelia is one of the first visual contact with #rakulang and is felt as something weird and not serious. this feeling persist as people are reading examples.

#rakulang is about zen (because the torture is for the implementors) so i really think that the zen gate from the rakudo page (or maybe something around the ying-yang which looks like a 6)  offers a much better signal than camelia does.

**Comment by AlexDaniel** [comment]
Even though I absolutely love camelia (the logo, the plushie, everything!), I do understand that others don't feel the same way. I'm personally up for seeing other options (for example butterfly logo reimaginations), but until there's some decent proposal it's too early to throw camelia away (or even suggest that it should be thrown away).

**Comment by jnthn** [comment]
The reviewers [considered and established a position on Camelia as a mascot](https://github.com/perl6/problem-solving/blob/master/solutions/language/Path-to-Raku.md#mascot) as recently as 2 months ago. Thus, this is summarily dismissed.

**Comment by AlexDaniel** [comment]
@jnthn that's simply untrue, getting a new mascot wasn't really considered or established. The document basically says that when it comes to the language rename no changes to the mascot will be made, it doesn't mean that everyone is entirely satisfied with the current state of things. And indeed, we wouldn't have made the progress on the renaming issue if we brought changes to the mascot into the path to raku PR.

The problem with the logo is being brought up regularly, I don't see the point in trying to pretend it's not there. Instead, I suggest we keep this ticket open for people to propose their well-designed logos. Who knows, maybe there's something new we can all potentially like.

**Comment by AlexDaniel** [comment]
[Also](https://raw.githubusercontent.com/perl6/mu/master/misc/camelia.txt):

> So let me summarize the requirements into a meta-requirement:
> >  The new logo must make Larry at least as happy as Camelia does.
>
> That is the extent to which my mind is still open...  :-)
> Larry

Which again means that we can be open to awesome logo proposals.

**Comment by AlexDaniel** [comment]
@jnthn I've changed the title of this ticket to something more pleasant, please consider reopening :)

**Comment by jnthn** [comment]
> that's simply untrue, getting/not getting a new mascot wasn't really considered or established

I gave my approval to a PR that precisely says:

> Camelia will remain the mascot

It was important to me that this was present, and certainly a factor in my decision to vote for the name change.

**Comment by AlexDaniel** [comment]
> I gave my approval to a PR that precisely says:

There was clearly a misunderstanding somewhere, because I gave my approval thinking that it doesn't mean that the mascot will have to remain like this forever. I understood it as we're simply leaving the mascot issue separate from the path to raku PR, and that the renaming process won't come with any changes to the mascot even though the mascot has “P 6” in it.

**Comment by duncand** [comment]
> I gave my approval to a PR that precisely says:
> 
> > Camelia will remain the mascot
> 
> It was important to me that this was present, and certainly a factor in my decision to vote for the name change.

The only thing this part and similar statements in the name change proposal meant is that the scope of the vote was being limited to very specific changes.  It did NOT mean that further changes would never be made.  It only meant wisely we were avoiding straying into omnibus bill territory.

Whether or not Camelia remains the mascot is best being its own independent decision.  If it is important to you that the mascot not change, then vote/argue against that change on its own merits.

**Comment by jnthn** [comment]
> It only meant wisely we were avoiding straying into omnibus bill territory.

Who is "we"? I was substantially involved in the path to raku PR and the process leading up to it, and while working on that I was pretty much certain that an issue like this would be opened. And I knew, 2-3 months back, that I was going to close it by pointing at the text I did. I *explicitly planned for this*.

> then vote/argue against that change on its own merits

Well, yes, ultimately I can't stop somebody opening a PR on a mascot change, and would vote against it then - which makes the outcome a foregone conclusion.

**Comment by duncand** [comment]
> > It only meant wisely we were avoiding straying into omnibus bill territory.
> 
> Who is "we"?

The subset of the community that participated in the renaming discussion, and wrote the pull request.

I doubt anyone expected the document being voted on for the renaming would be the last word, and merely that it was a solid increment to get agreement on, a core decision, and keeping it more straightforward by explicitly not changing things that didn't have to be changed as part of the rename.  The mascot didn't have to be changed and was left out.

I personally am not advocating for the mascot to be changed but I also am not opposed to it.  But if there is something else it should make Larry happy.

**Comment by duncand** [comment]
The important detail about the mascot in the renaming vote is that the document was explicit that approving the rename did NOT also give carte blanche to change the mascot too.  Any change to the mascot would have to be separately approved and barring that hurdle would stay the same.

**Comment by vrurg** [comment]
@duncand I think you're mistaken. The paper states explicitly:

>Camelia will remain the mascot. The only thing that should change there is that it is the mascot of Raku rather than Perl 6. 

My English doesn't allow me to read it other than: _'the decision is taken and not to be changed'_.

**Comment by AlexDaniel** [comment]
> My English doesn't allow me to read it other than: 'the decision is taken and not to be changed'.

Where are you reading this?

Moreover:

> This document describes the steps to be taken to effectuate a rename of
`Perl 6` to `Raku`, as described in issue #81.

That document is about the rename. How people ended up treating it as a final word on all language aspects is completely beyond me.

**Comment by duncand** [comment]
@vrurg My English adds an implicit "for now" to that statement, which is the case for most statements in English that don't explicitly say "until the end of time" or such.  It is saying that, by default, Camelia is retained as the mascot for Raku, and that the mascot will not be changed as part of the process of renaming the language to Raku; it does not say that the mascot os blocked from being changed as an independent separate decision.

**Comment by jnthn** [comment]
I've nothing to add beyond:

* I've made my voting intention clear on any mascot change proposal
* I'm not willing to spend any more of my time on this topic, and thus will unsubscribe

**Comment by vrurg** [comment]
Perhaps I had too much of communication with lawyers and bureaucracy, but to me and official document doesn't have implicit parts. The document which passed such a high level of scrutiny  – especially.

**Comment by duncand** [comment]
> Perhaps I had too much of communication with lawyers and bureaucracy, but to me and official document doesn't have implicit parts. The document which passed such a high level of scrutiny – especially.

Fair enough.  But the document also didn't explicitly say "until the end of time" or such, so interpreting it as such is as much of an implicit part as "for now" is.

**Comment by duncand** [comment]
So personally I don't see leaving Camelia as the mascot to be a problem.  I like Camelia just fine.

While changing the language name was important and a big deal because it is fundamental to the language identity and is used everywhere, the mascot actually is used quite rarely and people can easily choose to either use it or avoid it if they want to.

Its not like people think badly of all the sports teams with goofy mascots.

So I support keeping Camelia by default and I support those who want to retain it, even if I don't agree that a final decision was actually made on the matter.

Really, this is a relatively minor issue and there's no problem leaving the mascot as is.

**Comment by AlexDaniel** [comment]
That's so weird. So we're not even open to discussing logo proposals just because we're committed to not discussing the topic?

It's also surprising that after fixing a long-standing naming issue we're back to the “it's actually OK there's nothing wrong!” mentality.

To be fair, this ticket falls under jnthn's supervision so if he decided that it's a waste of time then so be it. But I feel really weird, especially because now I'm learning that the path to raku doc decisions are somehow cast in stone even though nobody told me that it'd be that way and the document clearly doesn't say that. Hm.

![hand in the sand](https://news-images.vice.com/images/articles/meta/2014/11/13/australian-protesters-bury-their-heads-in-the-sand-to-protest-government-climate-policies-1415899909.jpg?crop=1xw:0.8529545454545454xh;center,center&resize=700:*)

**Comment by duncand** [comment]
> That's so weird. So we're not even open to discussing logo proposals just because we're committed to not discussing the topic?
> 
> It's also surprising that after fixing a long-standing naming issue we're back to the “it's actually OK there's nothing wrong!” mentality.

I feel that at least in the short term the logo is more of a TIMTOWTDI thing.  Raku has the iconography of a butterfly in the generic sense just as much as Camelia in a specific sense.  Most marketing I've seen uses the more generic butterfly iconography if anything and Camelia hasn't appeared on much other than the main website as a spokes bug plus as a plush.  There is nothing that says marketing must use Camelia.

Again, it is typical for sports teams to have goofy mascots, but how often do people think a team's mascot reflects badly on the team ... unless its something racist or such.

**Comment by niner** [comment]
We have already sacrificed a name that many of us have a deep emotional connection to and that connected us to a community on the marketing altar. Let us not throw away all our heritage and certainly not the part where we are bravest in an attempt to change the status quo.

**Comment by eiro** [comment]
i don't mean to revive anything painful but just wanted to make you aware that, based on my experience, for a person who are not experimented enough in programming to choose a language by identifying concepts and compare syntaxes  (which means newcomers but also managers), camelia is a no go signal. not only it's weird but it also says nothing about the raku language.

but this topic wasn't even discussed in this ticket. can we measure it ? what could be the real impact of raku ? if some people are motivated to work on it (with user feedbacks and so on), will the community care ?

**Comment by JJ** [comment]
I agree with Jonathan here. Let's not waste our time and energies on this.

**Comment by lizmat** [comment]
Perhaps we can be a little less in the face of newcomers: if you compare https://docs.raku.org with https://docs.python.org/3/ you will notice that the Python logo is much less prominent there then Camelia is.  The same for https://www.python.org vs https://raku.org .  Now, I'm as proud of Camelia as anybody, but it should not be a barrier for people to enter Raku, it should be a filter.  So I would be in favour or re-designing public websites making Camelia less prominent generally, and maybe create a separate page that goes full out on Camelia and how she came to be, and what Larry tried to achieve with it.

**Comment by AlexDaniel** [comment]
Hm, github doesn't have a good reason for locking an issue. Anyway, I changed it to something random, just to make sure it's not marked as “resolved” because nothing was resolved.

**Comment by AlexDaniel** [comment]
Actually, I'm reopening this because I've just read the last comment by @lizmat. It's an interesting idea I haven't thought about previously.

This is exactly the reason why I'd like these discussions to happen, instead of shutting them down prematurely for no good reason.

Indeed, we can have a less prominent use of the logo, or maybe in some cases no logo at all.

**Comment by JJ** [comment]
OK, let's then bring some hard data in.
![Captura de pantalla de 2019-12-22 20-12-07](https://user-images.githubusercontent.com/500/71326163-6a781c80-24f7-11ea-824b-871354b854b5.png)
This from the user survey last June, which I guess most of you have access (or you can request it from me or one of us). 13.5% percent say "It's childish". 35% it's perfect, and 40.5% it does not matter. That adds up to a 75% of "don't waste our time on this".
You want to change the appearance of some sites, which is BTW long overdue, fine, toning down or up or anything in between Camelia. That's a totally different thing to changing the logo. So let's please keep this closed together with the discussion on the logo.

**Comment by AlexDaniel** [comment]
> That adds up to a 75% of "don't waste our time on this".

*Just* 75%. Also keep in mind that those who got turned off by the logo did not even participate in that survey.

**Comment by JJ** [comment]
> > That adds up to a 75% of "don't waste our time on this".
> 
> _Just_ 75%. Also keep in mind that those who got turned off by the logo did not even participate in that survey.

Unless you have hard data on this, I'd consider the question, again, settled. Also, I'm going with @jnthn and unsubscribing from this issue.

**Comment by AlexDaniel** [comment]
@JJ I'm surprised that *you* are refusing to accept that there is selection bias in your “hard” data.

![hand in the sand](https://news-images.vice.com/images/articles/meta/2014/11/13/australian-protesters-bury-their-heads-in-the-sand-to-protest-government-climate-policies-1415899909.jpg?crop=1xw:0.8529545454545454xh;center,center&resize=700:*)

**Comment by lizmat** [comment]
@AlexDaniel: please read carefully.  @JJ said: "unless if **YOU** have hard data".  He never said that he had hard data, just that he had data.

**Comment by AlexDaniel** [comment]
@lizmat he literally started his comment with “OK, let's then bring some hard data in.”. Then the next comment goes “I'd consider the question, again, settled” as if some hard data was presented.

**Comment by lizmat** [comment]
It's harder data than "I've heard people say" "many people say" etc.  So it's hard in the sense that it is harder data than hearsay.  Selection bias is always an issue.  I think @jnthn has made it clear that the mascot is not up for debate.  So let's start a new issue making Camelia just as prominent as the Python logo on Python pages.

**Comment by AlexDaniel** [comment]
> So let's start a new issue making Camelia just as prominent as the Python logo on Python pages.

Can we somehow stop derailing perfectly fine tickets into dumpster fires?
