### ISSUE TITLE
Add tony-o to the list of reviewers

### ISSUE THREAD

**Issue by tony-o** [perl6/problem-solving#7]
Please add me to `meta`

**Comment by AlexDaniel** [comment]
Clarified on IRC: https://colabti.org/irclogger/irclogger_log/perl6?date=2019-04-09#l608

Shortcut: will do as soon as https://github.com/perl6/problem-solving/pull/2 is merged (Apr 15th), it is currently in the review process and I don't want to disturb that by doing changes to the document. You're free to leave you review anyway!
