### ISSUE TITLE
pl6anet.org will be discontinued breaking "Recent Blog Posts" on perl6.org

### ISSUE THREAD

**Issue by stmuk** [perl6/problem-solving#86]
Currently the right hand side of the perl6.org website "Recent Blog Posts" is dependent on an external system "pl6anet.org" via

https://github.com/perl6/perl6.org/blob/master/fetch-recent-blog-posts.pl

This system will be closing down in about 30 days time and will need someone to work on a replacement if the "Recent Blog Posts" box is to continue.

Hosting a replacement is easy and details  are at 

https://github.com/stmuk/pl6anet.org

**Comment by lizmat** [comment]
@stmuk: thank you for supporting this service all of this time.

**Comment by rba** [comment]
I will take over the hosting.

@stmuk: Are you the owner of the domain and can we take over it as well?

Without takeing a closer look, there are not date to migrate, right? These feeds are all still available an it's just aggregated. (?)

**Comment by stmuk** [comment]
@rba I'm the domain owner via Namecheap and it's about to expire. I can probably transfer if anyone wants it. You are correct about it just being datafeed based.

**Comment by rba** [comment]
@stmuk I think we should continue it, as is for the moment. I've using gandi.net as my current registrar with a separate handle for perl6-infra. I will take over the domain if this is ok for you. Please "unlock" for transfer. (https://www.namecheap.com/support/knowledgebase/article.aspx/258/84/what-should-i-do-to-transfer-a-domain-from-namecheap)

**Comment by stmuk** [comment]
@rba I have unlocked and have an auth code.

**Comment by rba** [comment]
@stmuk Thanks for letting me take over the domain. The transfer is finished. I've change DNS servers too. pl6anet.org is still pointing to your current hosting ip atm. Will move the build+hosting in the next few days. Update follows.

**Comment by AlexDaniel** [comment]
Thank you, @stmuk and @rba.

**Comment by stmuk** [comment]
@rba Thanks for all this! 

I'll be shutting down the service in about a week on the current server.

**Comment by stmuk** [comment]
migrated!! rba++

**Comment by cbk** [comment]
@rba  when will the new service be online, I want to update my URL for my blog.

**Comment by rba** [comment]
@cbk The service is online. Please update https://github.com/perl6/pl6anet.org/blob/master/perlanetrc directly (or via PR).

**Comment by cbk** [comment]
Thank you.
